services:

  db_auth_service:
    image: mysql:9.3
    container_name: db_auth_service
    restart: unless-stopped
    volumes:
      - dbfile:/var/lib/mysql
    env_file:
      - auth_service/.env_db
    networks:
      - app

  auth_service:
    container_name: auth_service
    build:
      context: auth_service/
      dockerfile: ./Dockerfile
    depends_on:
      - db_auth_service
      - redis
    ports:
      - "8228:8228"
    env_file:
      - auth_service/.env
    networks:
      - app

  redis:
    image: redis:8.0.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  dbfile:
    driver: local